version: "3.9"

services:
  flask_api:
    build:
      context: ./flaskapi
      dockerfile: Dockerfile
    container_name: captcha_flask_api
    ports:
      - "5000:5000"
    volumes:
      - ../flaskapi:/app
      - ../model:/model
    environment:
      - FLASK_ENV=development
      # - MODEL_PATH=/model/captcha_model.pt
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
