version: "3.9"

services:
  flask_api:
    build: ./flaskapi
    container_name: captcha_flask_api
    ports:
      - "5050:5000"
    # volumes:
    #   - ../flaskapi:/app
    #   - ../model:/model
    environment:
      - FLASK_ENV=development
      # - MODEL_PATH=/model/captcha_model.pt
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
